/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyEpicGame } from "./MyEpicGame";

export { MyEpicGame__factory } from "./factories/MyEpicGame__factory";
